[package]
name = "ambur-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmwasm-std = "2.2.2"
philabs-cw721-marketplace = { path = "./packages/philabs-cw721-marketplace", features = ["library"] }
rmcp = { version = "0.1.5", features = ["transport-io"] }
schemars = "0.8.22"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }